[package]
name = "arachnid"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
clap = "3.0.0-beta.2"
ansi_term = "0.12.1"
